name: finvault
description: Professional Personal Finance Manager
publish_to: 'none'
version: 1.3.0+3  # Updated version for clean build

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # State Management
  provider: ^6.0.5
  
  # Navigation
  go_router: ^12.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  
  
  # Phase 3 - Charts & Analytics
  fl_chart: ^0.66.0
  
  # Phase 3 - Export & File Operations
  csv: ^5.0.2
  pdf: ^3.10.7
  printing: ^5.12.0
  file_picker: ^8.0.0
  share_plus: ^7.2.1
  permission_handler: ^11.1.0

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
